---
- hosts: all
  roles:
    - common

- name: rabbitmq used by openstack
  hosts: controller
  serial: 1
  roles:
    - rabbitmq

- name: install common percona components and gather facts
  hosts: db
  roles:
    - percona-common

- name: install percona on primary
  hosts: db[0]
  vars:
    should_bootstrap_as_primary: True
  roles:
    - percona-server

- name: install percona on secondaries
  hosts: db:!db[0]
  vars:
    should_bootstrap_as_primary: False
  roles:
    - percona-server

- name: install percona arbiter
  hosts: db_arbiter
  roles:
    - percona-common
    - percona-arbiter

- name: configure percona backups on primary
  hosts: db[0]
  roles:
    - percona-backup

- name: nova code and config
  hosts: controller:db:compute
  vars_files:
    - roles/memcached/defaults/main.yml
    - roles/rabbitmq/defaults/main.yml
  roles:
    - nova-common

- name: neutron code and config
  hosts: controller:db:compute:network
  vars_files:
    - roles/rabbitmq/defaults/main.yml
  roles:
    - neutron-common

- name: glance code and config
  hosts: controller:db
  roles:
    - glance-common

- name: keystone code and config
  hosts: controller:db
  vars_files:
    - roles/memcached/defaults/main.yml
  roles:
    - keystone-common

- name: cinder code and config
  hosts: controller:db:compute
  vars_files:
    - roles/rabbitmq/defaults/main.yml
  roles:
    - cinder-common

- name: dbs, db users, db schema updates
  hosts: db[0]
  roles:
    - db

- name: openstack client tools
  hosts: all
  roles:
    - client

- name: openstack controller services
  hosts: controller
  roles:
    - memcached
    - horizon
    - controller

- hosts: compute
  roles:
    - compute
    - cinder-volume

- hosts: network:compute
  roles:
    - openvswitch

- name: openstack network services
  hosts: network
  roles:
    - network

- hosts: controller[0]
  roles:
    - openstack-setup

- name: Install monitoring
  include: playbooks/monitoring.yml
