---
dependencies:
  - role: apt-repos
    repos:
        # TODO add OVS -master apt repository
      - repo: 'deb {{ apt_repos.bbg_openstack_ppa.repo }} precise main'
        key_url: '{{ apt_repos.bbg_openstack_ppa.key_url }}'
